server:
  base_url: http://localhost:8080
  port: 8080
  frontend_url: http://localhost:5173
  mode: debug
  id: 1
database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: yaccount
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "examplekey"
  expire: 1h

log:
  level: info
  filename: logs/example.log
  max_size: 10
  max_backups: 3
  max_age: 7
  compress: true
  rotate_daily: true
  console: true
  logs_dir: logs

middleware:
  jwt:
    secret: "examplekey"
    expire: 1h
    skip_paths:
      - /api/account/v1/auth/login
      - /api/account/v1/auth/register
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allow_headers:
      - Authorization

casdoor:
  host: http://localhost:8000
  client:
    endpoint: http://localhost:8000
    client_id: clientId
    client_secret: clientSecret
    certificate: certificate
    organization_name: organizationName
    application_name: applicationName